=== UW-Float-Lab/UW-floats-json/UWschema/UW_schema_L0.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "UW argo float L0 json",
  "description": "UW argo float L0 json, version 0.3.2, updated 2026-04-27",
  
  "$defs": {
    "ISO8601": {
      "$comment": "Timestamp in ISO 8601 format",
      "type": "string",
      "format": "date-time",
      "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$"
    },
    "semanticVersion": {
      "$comment": "String pattern that conforms to semantic versioning",
      "type": "string",
      "pattern": "^[0-9]+\\.[0-9]+\\.[0-9]+$"
    },
    "latitude": {
      "$comment": "Latitude in degree, positive -> north",
      "type": "number",
      "minimum": -90,
      "maximum": 90
    },
    "longitude": {
      "$comment": "Longitude in degree, positive -> east",
      "type": "number",
      "minimum": -180,
      "maximum": 180
    }
  },
  
  "type": "object",
  "properties": {
    "FILE_CREATION_DATE": {
      "description": "Timestamp of json file creation",
      "$ref": "#/$defs/ISO8601"
    },
    "FILE_UPDATE_DATE": {
      "description": "Timestamp of the latest json file update",
      "$ref": "#/$defs/ISO8601"
    },
    "DECODER_VERSION": {
      "description": "Version of the json decoder used to generate the document",
      "$ref": "#/$defs/semanticVersion"
    },
    "SCHEMA_VERSION": {
      "description": "Version of the json schema used to validate the document",
      "$ref": "#/$defs/semanticVersion"
    },
    "INTERNAL_ID_NUMBER": {
      "description": "UW Internal ID number for the float",
      "type": "integer"
    },
    "AOML_ID_NUMBER": {
      "description": "AOML ID number",
      "type": "integer"
    },
    "WMO_ID_NUMBER": {
      "description": "WMO ID number",
      "type": "integer"
    },
    "TRANSMISSION_ID_NUMBER": {
      "description": "[[TO BE SPECIFIED]]",
      "type": "integer"
    },
    "INSTRUMENT_TYPE": {
      "description": "the type of float",
      "type": "string",
      "enum": ["UW-APEX-core", "UW-APEX-BGC", "UW-NAVIS-BGC"]
    },
    "PI": {
      "description": "Principal investigator(s) associated with the float",
      "type": "string"
    },
    "OPERATING_INSTITUTION": {
      "description": "Institution responsible for operating the float",
      "type": "string",
      "const": "UW, Seattle, WA"
    },
    "FILE_CREATION_INSTITUTION": {
      "description": "Institution responsible for creating the json file",
      "type": "string",
      "const": "UW, Seattle, WA"
    },
    "PROJECT_NAME": {
      "description": "The project under which the float operates",
      "type": "string"
    },
    "CYCLE_NUMBER": {
      "description": "The profile number associated with the json file",
      "type": "integer"
    },
    "POSITIONING_SYSTEM": {
      "description": "The positioning system used to obtain latitude and longitude",
      "type": ["string", "null"],
      "enum": ["GPS", "Iridium", null]
    },
    "GPS": {
      "description": "Information about GPS coordinates fix",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "TIME": {
            "description": "Timestamp of the GPS fix",
            "$ref": "#/$defs/ISO8601"
          },
          "LATITUDE": {
            "description": "Latitude reading of the GPS fix",
            "$ref": "#/$defs/latitude"
          },
          "LONGITUDE": {
            "description": "Longitude reading of the GPS fix",
            "$ref": "#/$defs/longitude"
          },
          "sat_cnt": {
            "description": "Number of satellites used for the GPS fix",
            "type": "integer",
            "minimum": 1
          },
          "time_to_fix": {
            "description": "Time passed before GPS coordinates are fixed",
            "type": "integer",
            "minimum": 0
          },
          "description": {
            "description": "Description of the nature of the GPS fix",
            "type": "string"
          }
        },
        "additionalProperties": false,
        "required": [
          "TIME", "LATITUDE", "LONGITUDE"
        ]
      },
      "minItems": 1
    },
    "Iridium": {
      "description": "Iridium geolocation data transmitted.",
      "type": "array",
      "items": {
        "description": "Iridium's coordinates <x>, <y>, <z> form a geolocation grid code from an earth centered cartesian coordinate system, using dimensions, x, y, and z, to specify location. The coordinate system is aligned such that the z-axis is aligned with the north and south poles, leaving the x-axis and y-axis to lie in the plane containing the equator.  The axes are aligned such that at 0 degrees latitude and 0 degrees longitude, both y and z are zero and x is positive",
        "type": "object",
        "properties": {
          "x": {
            "description": "Iridium's x-coordinate, in km",
            "type": "number"
          },
          "y": {
            "description": "Iridium's y-coordinate, in km",
            "type": "number"
          },
          "z": {
            "description": "Iridium's z-coordinate, in km",
            "type": "number"
          },
          "TIME": {
            "description": "Decoded Iridium time",
            "$ref": "#/$defs/ISO8601"
          },
          "LATITUDE": {
            "description": "Latitude estimated by the Iridium system",
            "$ref": "#/$defs/latitude"
          },
          "LONGITUDE": {
            "description": "Longitude estimated by the Iridium system",
            "$ref": "#/$defs/longitude"
          },
          "system_time": {
            "description": "Iridium system time",
            "type": "integer",
            "minimum": 0
          }
        },
        "required": [
          "TIME", "LATITUDE", "LONGITUDE",
          "x", "y", "z"
        ],
        "additionalProperties": false
      },
      "minItems": 1
    },
    "Timestamps": {
      "type": "object",
      "properties": {
        "StartDescent": {
          "description": "Time at which the float started descending",
          "$ref": "#/$defs/ISO8601"
        },
        "StartPark": {
          "description": "Time at which the float started the parking phase",
          "$ref": "#/$defs/ISO8601"
        },
        "StartProfileDescent": {
          "description": "Time at which the float started descending for profiling",
          "$ref": "#/$defs/ISO8601"
        },
        "StartProfile": {
          "description": "Time at which the float started profiling",
          "$ref": "#/$defs/ISO8601"
        },
        "StopProfile": {
          "description": "Time at which the float stopped profiling",
          "$ref": "#/$defs/ISO8601"
        },
        "StartTelemetry": {
          "description": "Time at which the float started telemetry",
          "$ref": "#/$defs/ISO8601"
        }
      },
      "required": [],
      "additionalProperties": false
    },
    "CTD_Discrete": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "PRES": {
            "description": "Pressure, measured in dbar",
            "type": "number"
          },
          "TEMP": {
            "description": "Temperature, measured in celcius",
            "type": "number"
          },
          "PSAL": {
            "description": "Practical salinity",
            "type": "number"
          },
          "Temp_optode": {
            "description": "Temperature (in celsius) as measured by the optode sensor",
            "type": "number"
          },
          "TPhase": {
            "description": "TPhase (in [[???]]) as measured by optode sensor",
            "type": "number"
          },
          "RPhase": {
            "description": "RPhase (in [[???]]) as measured by the optode sensor",
            "type": "number"
          },
          "NO3": {
            "description": "Nitrate concentration from MBARI ISUS sensor in micromolar units",
            "type": ["null", "number"]
          },
          "pH_V": {
            "description": "MBARI ISUS pH sensor raw voltage (in volts)",
            "type": ["null", "number"]
          },
          "FSig": {
            "description": "Raw count of fluorescence",
            "type": "integer"
          },
          "BbSig": {
            "description": "Raw count of backscatter",
            "type": "integer"
          },
          "TSig": {
            "description": "Fluorometer Raw temperature signal",
            "type": "integer"
          },
          "Ocr": {
            "description": "four 32-bit channels of downwelling radiance reported by the OCR-504. Each array element represent 32-bit ADC values",
            "type": "array",
            "minItems": 4,
            "maxItems": 4,
            "items": {
                "type": ["null", "integer"]
            }
          }
        },
        "required": [
          "PRES", "TEMP", "PSAL"
        ],
        "additionalProperties": false
      },
      "minItems": 1
    },
    "CTD_Binned": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "PRES": {
            "description": "Pressure, measured in dbar",
            "type": "number"
          },
          "TEMP": {
            "description": "Temperature, measured in celcius",
            "type": "number"
          },
          "PSAL": {
            "description": "Practical salinity",
            "type": "number"
          },
          "n_samp": {
            "description": "Number of samples",
            "type": "integer"
          }
        },
        "required": [
          "PRES", "TEMP", "PSAL", "n_samp"
        ],
        "additionalProperties": false
      },
      "minItems": 1
    },
    "CTD_Drift": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "PRES": {
            "description": "Pressure, measured in dbar",
            "type": "number"
          },
          "TEMP": {
            "description": "Temperature, measured in celcius",
            "type": "number"
          },
          "PSAL": {
            "description": "Practical salinity",
            "type": "number"
          },
          "FSig": {
            "description": "Raw count of fluorescence",
            "type": "integer"
          },
          "BbSig": {
            "description": "Raw count of backscatter",
            "type": "integer"
          },
          "TSig": {
            "description": "Fluorometer Raw temperature signal",
            "type": "integer"
          },
          "TIME": {
            "description": "Time at which the CTD data is taken",
            "$ref": "#/$defs/ISO8601"
          }
        },
        "required": [
          "PRES", "TEMP", "TIME"
        ],
        "additionalProperties": false
      },
      "minItems": 1
    },
    "optode_air_calibration": {
      "description": "Samples collected at the surface just before and just after the pneumatic bladder is inflated. The samples collected just before inflation are intended to collect optode samples in-water very near the surface. The samples collected just after inflation are intended to represent samples collected in-air.", 
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "Pres_air": {
            "description": "Pressure (in A/D counts) of the pneumatic bladder which is less than 90 for a deflated bladder and greater than 115 for an inflated bladder",
            "type": "integer"
          },
          "Pres_CTD": {
            "description": "Pressure (in dbar) as measured by the CTD",
            "type": "number"
          },
          "Temp_optode": {
            "description": "Temperature (in celsius) as measured by the optode sensor",
            "type": "number"
          },
          "TPhase": {
            "description": "TPhase (in [[???]]) as measured by optode sensor",
            "type": "number"
          },
          "RPhase": {
            "description": "RPhase (in [[???]]) as measured by the optode sensor",
            "type": "number"
          },
          "FSig": {
            "description": "Raw count of fluorescence",
            "type": "integer"
          },
          "BbSig": {
            "description": "Raw count of backscatter",
            "type": "integer"
          },
          "TSig": {
            "description": "Fluorometer Raw temperature signal",
            "type": "integer"
          },
          "Ocr": {
            "description": "four 32-bit channels of downwelling radiance reported by the OCR-504. Each array element represent 32-bit ADC values",
            "type": "array",
            "minItems": 4,
            "maxItems": 4,
            "items": {
                "type": "integer"
            }
          }
        }
      },
      "additionalProperties": false
    },
    "dura": {
      "description": "Data and metadata from Dura sensor. [[More details to be added]]",
      "type": "object",
      "properties": {
        "science_data": {
          "description": "Science data contained in the .dura file",
          "type": "array",
          "items": {
            "type": "object"
          },
          "minItems": 1
        },
        "engineering_data": {
          "description": "Engineering data contained in the .dura file",
          "type": "array",
          "items": {
            "type": "object"
          },
          "minItems": 1
        }
      },
      "additionalProperties": false,
      "required": [
        "science_data",
        "engineering_data"
      ]
    },
    "isus": {
      "description": "Data and metadata from Isus sensor. [[More details to be added]]",
      "type": "object",
      "properties": {
        "science_data": {
          "description": "Science data contained in the .isus file",
          "type": "array",
          "items": {
            "type": "object"
          },
          "minItems": 1
        },
        "engineering_data": {
          "description": "Engineering data contained in the .isus file",
          "type": "array",
          "items": {
            "type": "object"
          },
          "minItems": 1
        }
      },
      "additionalProperties": false,
      "required": [
        "science_data",
        "engineering_data"
      ]
    },
    "ARGO_Mission": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "value": {
            "description": "Value of the corresponding mission parameter",
            "type": "string"
          },
          "unit": {
            "description": "Unit of the corresponding mission parameter, if applicable",
            "type": "string"
          }
        },
        "required": [ "value" ]
      }
    },
    "Engineering_Data": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": {
          "anyOf": [
            { 
              "type": "string"
            },
            {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          ]
        }
      }
    },
    "Log": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "datetime": {
            "description": "the date and time at which the function call is made",
            "$ref": "#/$defs/ISO8601"
          },
          "mission_time": {
            "description": "Mission time at which the function call is made, in seconds",
            "type": "integer",
            "minimum": 0
          },
          "call": {
            "description": "The function that logged the message",
            "type": "string"
          },
          "message": {
            "description": "The message logged by the function",
            "type": "string"
          }
        },
        "required": ["datetime", "mission_time", "call", "message"],
        "additionalProperties": false
      }
    }
  },
  "additionalProperties": false,
  "required": [
    "FILE_CREATION_DATE",
    "FILE_UPDATE_DATE",
    "DECODER_VERSION",
    "SCHEMA_VERSION",
    "INTERNAL_ID_NUMBER",
    "AOML_ID_NUMBER",
    "WMO_ID_NUMBER",
    "TRANSMISSION_ID_NUMBER",
    "INSTRUMENT_TYPE",
    "OPERATING_INSTITUTION",
    "FILE_CREATION_INSTITUTION",
    "PI",
    "PROJECT_NAME",
    "CYCLE_NUMBER",
    "POSITIONING_SYSTEM"
  ]
}

=== UW-Float-Lab/UW-floats-json/examples/output/09968/09968_023031_L0_0035.json
{
  "FILE_CREATION_DATE": "2026-04-23T21:23:26Z",
  "FILE_UPDATE_DATE": "2026-04-23T21:23:26Z",
  "DECODER_VERSION": "0.3.1",
  "SCHEMA_VERSION": "0.3.1",
  "INTERNAL_ID_NUMBER": 23031,
  "TRANSMISSION_ID_NUMBER": 23031,
  "AOML_ID_NUMBER": 9968,
  "WMO_ID_NUMBER": 7902024,
  "INSTRUMENT_TYPE": "UW-APEX-core",
  "OPERATING_INSTITUTION": "UW, Seattle, WA",
  "FILE_CREATION_INSTITUTION": "UW, Seattle, WA",
  "PI": "RISER, STEVE AND GRAY, ALISON",
  "PROJECT_NAME": "Core Float",
  "CYCLE_NUMBER": 35,
  "POSITIONING_SYSTEM": "GPS",
  "Timestamps": {
    "StartDescent": "2025-11-01T16:52:50Z",
    "StartPark": "2025-11-01T20:52:49Z",
    "StartProfileDescent": "2025-11-11T12:53:43Z",
    "StartProfile": "2025-11-11T16:52:49Z",
    "StopProfile": "2025-11-11T22:51:41Z",
    "StartTelemetry": "2025-11-11T22:54:04Z"
  },
  "GPS": [
    {
      "description": "GPS_FIX",
      "TIME": "2025-11-11T23:05:30Z",
      "LATITUDE": -44.3823,
      "LONGITUDE": -101.3038,
      "sat_cnt": 9,
      "time_to_fix": 42
    }
  ],
  "Iridium": [
    {
      "LATITUDE": -44.331,
      "LONGITUDE": -101.467,
      "TIME": "2025-11-01T16:48:48Z",
      "x": -908.0,
      "y": -4476.0,
      "z": -4432.0,
      "system_time": 4024416596
    }
  ],
  "CTD_Discrete": [
    {
      "PRES": 1003.57,
      "TEMP": 4.2289,
      "PSAL": 34.2875
    },
    {
      "PRES": 1997.35,
      "TEMP": 2.2946,
      "PSAL": 34.6339
    },
    {
      "PRES": 1948.25,
      "TEMP": 2.3372,
      "PSAL": 34.6226
    },
    {
      "PRES": 1898.47,
      "TEMP": 2.3773,
      "PSAL": 34.6136
    },
    {
      "PRES": 1848.35,
      "TEMP": 2.4245,
      "PSAL": 34.603
    },
    {
      "PRES": 1798.56,
      "TEMP": 2.4775,
      "PSAL": 34.5913
    },
    {
      "PRES": 1748.55,
      "TEMP": 2.5378,
      "PSAL": 34.5783
    },
    {
      "PRES": 1697.72,
      "TEMP": 2.6037,
      "PSAL": 34.5646
    },
    {
      "PRES": 1648.75,
      "TEMP": 2.6688,
      "PSAL": 34.55
    },
    {
      "PRES": 1598.7,
      "TEMP": 2.7392,
      "PSAL": 34.5338
    },
    {
      "PRES": 1548.21,
      "TEMP": 2.8145,
      "PSAL": 34.5164
    },
    {
      "PRES": 1498.65,
      "TEMP": 2.8745,
      "PSAL": 34.4976
    },
    {
      "PRES": 1448.97,
      "TEMP": 2.9851,
      "PSAL": 34.476
    },
    {
      "PRES": 1398.97,
      "TEMP": 3.0281,
      "PSAL": 34.4529
    },
    {
      "PRES": 1348.15,
      "TEMP": 3.1327,
      "PSAL": 34.4282
    },
    {
      "PRES": 1299.0,
      "TEMP": 3.2321,
      "PSAL": 34.4067
    },
    {
      "PRES": 1249.11,
      "TEMP": 3.3517,
      "PSAL": 34.3841
    },
    {
      "PRES": 1198.71,
      "TEMP": 3.4979,
      "PSAL": 34.3586
    },
    {
      "PRES": 1149.11,
      "TEMP": 3.6771,
      "PSAL": 34.3358
    },
    {
      "PRES": 1098.95,
      "TEMP": 3.8789,
      "PSAL": 34.3176
    },
    {
      "PRES": 1047.9,
      "TEMP": 4.085,
      "PSAL": 34.3008
    },
    {
      "PRES": 998.79,
      "TEMP": 4.3785,
      "PSAL": 34.2797
    }
  ],
  "CTD_Binned": [
    {
      "PRES": 4.4,
      "TEMP": 10.436,
      "PSAL": 34.011,
      "n_samp": 14
    },
    {
      "PRES": 6.0,
      "TEMP": 10.43,
      "PSAL": 34.011,
      "n_samp": 21
    },
    {
      "PRES": 8.0,
      "TEMP": 10.431,
      "PSAL": 34.011,
      "n_samp": 23
    },
    {
      "PRES": 10.0,
      "TEMP": 10.431,
      "PSAL": 34.011,
      "n_samp": 22
    },
    {
      "PRES": 12.0,
      "TEMP": 10.433,
      "PSAL": 34.011,
      "n_samp": 24
    },
    {
      "PRES": 14.0,
      "TEMP": 10.432,
      "PSAL": 34.011,
      "n_samp": 28
    },
    {
      "PRES": 16.0,
      "TEMP": 10.43,
      "PSAL": 34.011,
      "n_samp": 30
    },
    {
      "PRES": 18.0,
      "TEMP": 10.428,
      "PSAL": 34.01,
      "n_samp": 29
    },
    {
      "PRES": 20.0,
      "TEMP": 10.407,
      "PSAL": 34.011,
      "n_samp": 28
    },
    {
      "PRES": 22.0,
      "TEMP": 10.388,
      "PSAL": 34.01,
      "n_samp": 28
    },
    {
      "PRES": 24.0,
      "TEMP": 10.372,
      "PSAL": 34.01,
      "n_samp": 28
    },
    {
      "PRES": 26.0,
      "TEMP": 10.358,
      "PSAL": 34.008,
      "n_samp": 27
    },
    {
      "PRES": 28.0,
      "TEMP": 10.298,
      "PSAL": 34.009,
      "n_samp": 26
    },
    {
      "PRES": 30.0,
      "TEMP": 10.151,
      "PSAL": 34.013,
      "n_samp": 25
    },
    {
      "PRES": 32.0,
      "TEMP": 10.01,
      "PSAL": 34.022,
      "n_samp": 24
    },
    {
      "PRES": 34.0,
      "TEMP": 9.843,
      "PSAL": 34.032,
      "n_samp": 23
    },
    {
      "PRES": 36.0,
      "TEMP": 9.72,
      "PSAL": 34.041,
      "n_samp": 23
    },
    {
      "PRES": 38.0,
      "TEMP": 9.686,
      "PSAL": 34.041,
      "n_samp": 22
    },
    {
      "PRES": 40.0,
      "TEMP": 9.663,
      "PSAL": 34.042,
      "n_samp": 21
    },
    {
      "PRES": 42.0,
      "TEMP": 9.651,
      "PSAL": 34.042,
      "n_samp": 22
    },
    {
      "PRES": 44.0,
      "TEMP": 9.622,
      "PSAL": 34.044,
      "n_samp": 21
    },
    {
      "PRES": 46.0,
      "TEMP": 9.594,
      "PSAL": 34.044,
      "n_samp": 21
    },
    {
      "PRES": 48.0,
      "TEMP": 9.58,
      "PSAL": 34.043,
      "n_samp": 21
    },
    {
      "PRES": 50.0,
      "TEMP": 9.51,
      "PSAL": 34.046,
      "n_samp": 21
    },
    {
      "PRES": 52.0,
      "TEMP": 9.455,
      "PSAL": 34.047,
      "n_samp": 21
    },
    {
      "PRES": 54.0,
      "TEMP": 9.411,
      "PSAL": 34.047,
      "n_samp": 21
    },
    {
      "PRES": 56.0,
      "TEMP": 9.39,
      "PSAL": 34.046,
      "n_samp": 21
    },
    {
      "PRES": 58.0,
      "TEMP": 9.325,
      "PSAL": 34.049,
      "n_samp": 20
    },
    {
      "PRES": 60.0,
      "TEMP": 9.256,
      "PSAL": 34.05,
      "n_samp": 20
    },
    {
      "PRES": 62.0,
      "TEMP": 9.225,
      "PSAL": 34.05,
      "n_samp": 20
    },
    {
      "PRES": 64.0,
      "TEMP": 9.188,
      "PSAL": 34.051,
      "n_samp": 20
    },
    {
      "PRES": 66.0,
      "TEMP": 9.16,
      "PSAL": 34.051,
      "n_samp": 20
    },
    {
      "PRES": 68.0,
      "TEMP": 9.117,
      "PSAL": 34.053,
      "n_samp": 19
    },
    {
      "PRES": 70.0,
      "TEMP": 9.085,
      "PSAL": 34.054,
      "n_samp": 19
    },
    {
      "PRES": 71.9,
      "TEMP": 9.055,
      "PSAL": 34.055,
      "n_samp": 19
    },
    {
      "PRES": 74.0,
      "TEMP": 9.037,
      "PSAL": 34.055,
      "n_samp": 19
    },
    {
      "PRES": 76.0,
      "TEMP": 9.023,
      "PSAL": 34.056,
      "n_samp": 19
    },
    {
      "PRES": 78.0,
      "TEMP": 9.003,
      "PSAL": 34.057,
      "n_samp": 20
    },
    {
      "PRES": 80.0,
      "TEMP": 8.965,
      "PSAL": 34.056,
      "n_samp": 18
    },
    {
      "PRES": 82.0,
      "TEMP": 8.95,
      "PSAL": 34.056,
      "n_samp": 19
    },
    {
      "PRES": 84.0,
      "TEMP": 8.899,
      "PSAL": 34.058,
      "n_samp": 19
    },
    {
      "PRES": 86.0,
      "TEMP": 8.837,
      "PSAL": 34.057,
      "n_samp": 18
    },
    {
      "PRES": 88.0,
      "TEMP": 8.805,
      "PSAL": 34.057,
      "n_samp": 19
    },
    {
      "PRES": 90.0,
      "TEMP": 8.748,
      "PSAL": 34.057,
      "n_samp": 18
    },
    {
      "PRES": 92.0,
      "TEMP": 8.715,
      "PSAL": 34.056,
      "n_samp": 19
    },
    {
      "PRES": 94.0,
      "TEMP": 8.674,
      "PSAL": 34.057,
      "n_samp": 18
    },
    {
      "PRES": 96.0,
      "TEMP": 8.62,
      "PSAL": 34.06,
      "n_samp": 18
    },
    {
      "PRES": 98.0,
      "TEMP": 8.565,
      "PSAL": 34.056,
      "n_samp": 18
    },
    {
      "PRES": 100.0,
      "TEMP": 8.556,
      "PSAL": 34.056,
      "n_samp": 18
    },
    {
      "PRES": 102.1,
      "TEMP": 8.547,
      "PSAL": 34.056,
      "n_samp": 20
    },
    {
      "PRES": 104.0,
      "TEMP": 8.514,
      "PSAL": 34.055,
      "n_samp": 22
    },
    {
      "PRES": 106.0,
      "TEMP": 8.497,
      "PSAL": 34.054,
      "n_samp": 26
    },
    {
      "PRES": 108.0,
      "TEMP": 8.494,
      "PSAL": 34.054,
      "n_samp": 27
    },
    {
      "PRES": 110.0,
      "TEMP": 8.49,
      "PSAL": 34.053,
      "n_samp": 27
    },
    {
      "PRES": 112.0,
      "TEMP": 8.478,
      "PSAL": 34.053,
      "n_samp": 27
    },
    {
      "PRES": 114.0,
      "TEMP": 8.458,
      "PSAL": 34.054,
      "n_samp": 27
    },
    {
      "PRES": 116.0,
      "TEMP": 8.438,
      "PSAL": 34.055,
      "n_samp": 26
    },
    {
      "PRES": 118.0,
      "TEMP": 8.437,
      "PSAL": 34.063,
      "n_samp": 26
    },
    {
      "PRES": 120.0,
      "TEMP": 8.402,
      "PSAL": 34.068,
      "n_samp": 26
    },
    {
      "PRES": 122.0,
      "TEMP": 8.353,
      "PSAL": 34.068,
      "n_samp": 25
    },
    {
      "PRES": 124.0,
      "TEMP": 8.321,
      "PSAL": 34.069,
      "n_samp": 25
    },
    {
      "PRES": 126.0,
      "TEMP": 8.299,
      "PSAL": 34.07,
      "n_samp": 25
    },
    {
      "PRES": 128.0,
      "TEMP": 8.265,
      "PSAL": 34.071,
      "n_samp": 24
    },
    {
      "PRES": 130.0,
      "TEMP": 8.218,
      "PSAL": 34.076,
      "n_samp": 24
    },
    {
      "PRES": 132.0,
      "TEMP": 8.187,
      "PSAL": 34.076,
      "n_samp": 23
    },
    {
      "PRES": 134.0,
      "TEMP": 8.176,
      "PSAL": 34.078,
      "n_samp": 24
    },
    {
      "PRES": 136.0,
      "TEMP": 8.156,
      "PSAL": 34.084,
      "n_samp": 22
    },
    {
      "PRES": 138.0,
      "TEMP": 8.153,
      "PSAL": 34.09,
      "n_samp": 23
    },
    {
      "PRES": 140.0,
      "TEMP": 8.136,
      "PSAL": 34.096,
      "n_samp": 22
    },
    {
      "PRES": 142.0,
      "TEMP": 8.124,
      "PSAL": 34.1,
      "n_samp": 23
    },
    {
      "PRES": 144.0,
      "TEMP": 8.113,
      "PSAL": 34.104,
      "n_samp": 22
    },
    {
      "PRES": 146.0,
      "TEMP": 8.102,
      "PSAL": 34.108,
      "n_samp": 21
    },
    {
      "PRES": 148.0,
      "TEMP": 8.092,
      "PSAL": 34.112,
      "n_samp": 21
    },
    {
